version: 2
jobs:
  unit:
    docker:
      - image: fishtownjacob/test-container
    steps:
      - checkout
      - run:
          name: install test requirements
          command: bash test/setup.sh

      - run:
          name: Run unit tests
          command: tox -e flake8,unit

workflows:
  version: 2
  test-everything:
    jobs:
      - unit
